@startuml
actor 用户
用户->测试服务:获取用例列表
测试服务<-Gitlab:事件触发接口通知
测试服务->Gitlab:产生变化拉取代码
Gitlab->测试服务:返回代码
测试服务->测试服务:扫描更新用例
测试服务->用户:返回用例
用户->测试服务:创建任务
database 数据库
测试服务->数据库:创建任务
测试服务->用户:返回任务ID
测试服务->测试服务:异步编译执行任务
测试服务->数据库:更新任务状态
测试服务->文件服务:存储测试报告
用户->测试服务:获取测试结果
测试服务->数据库:查询完成状态的任务
测试服务->文件服务:获取测试报告
测试服务->用户:返回测试报告
@enduml
